### ISSUE TITLE
How to achieve transparent background

### ISSUE THREAD

**Issue by Create-Peace** [KevinSilvester/nvim-config-v3#4]
Hi, I see that the background of your nvim is transparent. How was this implemented?
[https://github.com/KevinSilvester/wezterm-config/blob/master/.github/screenshots/wezterm.gif](url)

**Comment by KevinSilvester** [comment]
I'm using the the plugin [`transparent.nvim`](https://github.com/xiyaowong/transparent.nvim) for this.

Currently have setup so that it is only enabled if the terminal emulator is wezterm. 
<https://github.com/KevinSilvester/nvim-config/blob/5b7ace239dfdb8056722068ce46d5d698d865524/lua/modules/ui/plugins.lua#L30-L42>

Hope this helps 🙂

**Comment by Create-Peace** [comment]
Thanks
